apiVersion: v1
kind: List
items:
{{ range $index, $hostname := .Values.volumeHosts }}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: "datadir-{{ $.Values.volumeBaseName }}-mongodb-{{ $index }}"
    namespace: {{ $.Release.Namespace }}
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: {{ $.Values.mongodb.storageSize | quote }}
    storageClassName: {{ $.Values.storageClass | quote }}
    volumeMode: "Filesystem"
{{- end }}
