apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.namespace.tlsSecret.name }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.namespace.tlsSecret.crtBase64 }}
  tls.key: {{ .Values.namespace.tlsSecret.keyBase64 }}
