apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rocketchat.fullname" . }}
type: Opaque
data:
{{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}