apiVersion: v1
kind: Service
metadata:
  name: {{ include "rocketchat.fullname" . }}
  labels:
{{- include "rocketchat.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "rocketchat.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
