# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

securityContext: {}

image: 
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  sessionAffinity: None
  port: 3000

ingress:
  annotations: {}

podSecurityContext: {}
  # fsGroup: 2000

deployment:
  rollingUpdate:
    maxSurge: 2
    maxUnavailable: 1

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}